[project]
name = "ffb-research"
version = "0.1.0"
description = "Make your own decisions!"
authors = [
    {name = "Sean Hannon",email = "seanhannon00@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nfl-data-py (>=0.3.3,<0.4.0)",
    "streamlit (>=1.41.1,<2.0.0)",
    "plotly (>=5.24.1,<6.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
